services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: .env # Should define POSTGRES_USER, POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres

networks:
  postgres: