[package]
name = "rust-tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41", features = ["async-await"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "chrono"] }
